### ISSUE TITLE
Help: How to statistic the memory, disk usage, apparent size

### ISSUE THREAD

**Issue by qiuming-best** [nh2/bupstash-kopia-comparison#1]
Hello, Could you help me with how to statistic the memory, disk usage, apparent size? thank you

**Comment by nh2** [comment]
Hey,

* to measure memory (resident RAM), run the program with `command time yourprogram`. It will print something like `... 85256maxresident)k`, so that example would be around 85 MB.
* to measure disk usage, use `du -sh /path/to/dir`
* to measure apparent size, use `du -sh --apparent-size /path/to/dir` (see `man du`)

You can also use the handy program `ncdu`, which is an `ncurses` based terminal UI program, where

* pressing the `a` key toggles between disk usage and apparent size
* pressing the `c` key can also show the number of files per subdirectory

Hope that helps!
